name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-cicd:1.0 .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/node-cicd:1.0

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/node-cicd:1.0
          docker stop nodeapp || true
          docker rm nodeapp || true
          docker run -d -p 80:3000 --name nodeapp ${{ secrets.DOCKER_USERNAME }}/node-cicd:1.0
